// ACCESS POINTS
export const DEVICES_NAMES_WHITE_LIST = ['ESP32-CAM'];

// [ACCESS_POINT]: [PASSWORD]
export const DEVICES_PASSWORDS = {
  'ESP32-CAM': 'esp32-cam-pass',
};
// [ACCESS_POINT]: [IP_ADDRESS]
export const DEVICES_DEFAULT_IP_ADDRESSES = {
  'ESP32-CAM': '192.168.4.1',
};
